### ISSUE TITLE
decreasingDots does not work correctly with dynamic data

### ISSUE THREAD

**Issue by pmtu95** [felire/react-native-animated-dots-carousel#5]
I'm using react-native-animated-dots-carousel and set the config:
```length: 8; maxIndicator: 5;```
when I set `currentIndex = 0` for render for the first time the  `decreasingDots` worked correctly.
![1](https://github.com/felire/react-native-animated-dots-carousel/assets/33753111/390c3672-7fde-4b55-b703-b0143993d0b4)

But if I update the `length = 7;  currentIndex = 6`, it will render wrong
![2](https://github.com/felire/react-native-animated-dots-carousel/assets/33753111/638e81a3-4751-4f0c-92bc-bb0725943c75)

expectation:
![3](https://github.com/felire/react-native-animated-dots-carousel/assets/33753111/bcf875b0-c36c-4192-b482-03a48c30407a)

**Comment by felire** [comment]
Why would you use dynamic data? I do not remember supporting it when I built it, or testing something with dynamic data

**Comment by tu-buuuk** [comment]
> Why would you use dynamic data? I do not remember supporting it when I built it, or testing something with dynamic data

because my carousel would fetch data from server and I can update on the list by adding/deleting items in the list. The issue came from when I changed currentIndex to the last position of the list and removed the last item, it will show like the second image but my expectation is the 3rd image

**Comment by pmtu95** [comment]
> Why would you use dynamic data? I do not remember supporting it when I built it, or testing something with dynamic data

because my carousel would fetch data from server and I can update on the list by adding/deleting items in the list. The issue came from when I changed currentIndex to the last position of the list and removed the last item, it will show like the second image but my expectation is the 3rd image

**Comment by felire** [comment]
@pmtu95 The only thing I can suggest you to do is to `re-render` the dots with the new data. Re render it completely
