### ISSUE TITLE
Add duration as prop

### ISSUE THREAD

**Issue by bpeck81** [felire/react-native-animated-dots-carousel#6]
I think this is a pretty simple change, but could you add the animation duration to go from one dot to the next as a prop? In the code it looks like it's 300ms, and from my experience with it, it feels a little slow and 200ms would probably make it feel more like instagram and other apps.

Thanks.

**Comment by felire** [comment]
Addressed here: [https://github.com/felire/react-native-animated-dots-carousel/pull/10](https://github.com/felire/react-native-animated-dots-carousel/pull/10)
